version: '3.8'
services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build: ./ariy_project
    env_file: ./ariy_project/.env
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped
