version: '3.8'
services:
  frontend:
    build: ./ariy_project
    volumes:
      - ./ariy_project:/app
    working_dir: /app
    command: npm build:dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:4000
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npx nodemon index.js
    ports:
      - "4000:4000"
    env_file: ./backend/.env
